### ISSUE TITLE
attention mechanism question

### ISSUE THREAD

**Issue by gmichalo** [aehrc/LAAT#4]
I was wondering why in line 108  you use the original embedding (x) of the text:
```
weighted_output = att_weights @ x
```
and not the weight variable (line 102, 104) that you use to calculate the attention weight:
```
att_weights = self.second_linears[label_level](weights)
```

**Comment by tienthanhdhcn** [comment]
Hi, the weight variable (line 102, 104) is only used to calculate the attention weight which then is used to calculate the weighted_output (similar to the weighting scheme). Also, x is the output of the LSTM layer and is not the output of the embedding layer. 

You can have a look at the paper and this link to see how the label attention work: https://drive.google.com/file/d/12e5AmbJ3uMRG9Lv8SmG-nsXsxhv-LY6e/view?usp=sharing
