### ISSUE TITLE
Issue with attention mechanism

### ISSUE THREAD

**Issue by MichalMalyska** [aehrc/LAAT#6]
It seems you are calculating the attention weights (in some settings) based on a linear transform of the inputs:
https://github.com/aehrc/LAAT/blob/cd5c0ec0b0b8098289042be6d68363a760d7bbca/src/models/attentions/attention_layer.py#L102

However you will always only apply the attentions to the original input (without applying the first_linears):
https://github.com/aehrc/LAAT/blob/cd5c0ec0b0b8098289042be6d68363a760d7bbca/src/models/attentions/attention_layer.py#L108

Is that a bug or am I missing something in the implementation? There is no mention of any of this in the original paper, just that d_a is a hyperparam.

**Comment by tienthanhdhcn** [comment]
Hi @MichalMalyska, it is not a bug, d_a is used to generate the attention weights only here. Line 102 and 108 are equations 4 and 6 respectively in the paper. See this https://github.com/aehrc/LAAT/issues/4 for some more information.

**Comment by MichalMalyska** [comment]
oh I see, first_linears is just the W matrix, this makes it clearer to me. Thank you!
