### ISSUE TITLE
Visualize the output of attention?

### ISSUE THREAD

**Issue by Abhinav43** [aehrc/LAAT#8]
Is it possible to explain the output of attention? Which token is contributing how much to the prediction? the depth of colour on each text represents the level of contribution such as bert visualizer etc?

**Comment by tienthanhdhcn** [comment]
@Abhinav43 this might be the code you want
[predictor_with_attention.zip](https://github.com/aehrc/LAAT/files/9038800/predictor_with_attention.zip)

**Comment by Abhinav43** [comment]
@tienthanhdhcn Thank you very much for the quick response. Could you please explain how to use it ? Any demo or use script? Which function to run first? Also, while going through the code, I couldn't find "code_desc.txt" anywhere in the folder?
